Database.langs = {
	fr: {
			"GET_GOLD": "Vous obtenez 7 Or",
			"GET_GOLD_2": "Vous obtenez 3 Or",
			"GET_GOLD_3": "Vous obtenez 5 Or",
			"PROHIBITED": "Entr�e interdite",
			"YEAHHHH": "Yeahhhhh",
			"SPEND": "Je vais passer la journ�e � enlever les mauvaises \nherbes",
			"HELP_US": "Aides-nous, ma fille a �t� kidnapp�e et \nemprisonn�e dans les catacombes � l'est du village\nAppuyez sur Espace pour quitter la boite de dialogue \net sur les fl�ches pour bouger",
			"WARRIOR": "Je suis une guerri�re sans arme. Il me semble \n qu'il y a une �p�e dans la grotte du village",
			"LEAVE": "Si tu quittes le village, soit vigilant !",
			"CALM": "Le village est calme",
			"BORED": "Je m'ennnuie",
			"COURAGE": "Tu m�rites une bonne r�compense pour ton courage",
			"MONEY": "Ne d�pense pas l'argent donn� inutilement !",
			"NEED_SWORD": "Tu as besoin d'une �p�e avant de quitter le village",
			"SWORD": "Vous recevez une �p�e",
			"PASS": "Tu peux passer seulement si tu me donnes 55 Or!",
			"GIVE_ME": "Domme moi 55 Or",
			"YOU_LOSE": "Vous perdez 55 Or",
			"TY": "Merci de m'avoir sauv� !"
		},
	en: {
			"GET_GOLD": "You get 7 Gold",
			"GET_GOLD_2": "You get 3 Gold",
			"GET_GOLD_3": "You get 5 Gold",
			"PROHIBITED": "Entry prohibited",
			"YEAHHHH": "Yeahhhhh",
			"SPEND": "I'll spend the day removing weeds",
			"HELP_US": "Help us, my daughter was kidnapped and imprisoned \nin the catacombs to the east of the village. \nPress the spacebar to exit the dialog box \nand the arrows to move",
			"WARRIOR": "I am a warrior without a weapon. It seems \nhe has a sword in a cave in the village",
			"LEAVE": "If you leave the city, be vigilant !",
			"CALM": "The city is calm.",
			"BORED": "I'm bored",
			"COURAGE": "You deserve a good reward for your courage",
			"MONEY": "Not spend money unnecessarily given !",
			"NEED_SWORD": "You need to have a sword before leaving the village",
			"SWORD": "You receive a sword",
			"PASS": "You can pass only if you give me 55 Gold!",
			"GIVE_ME": "Give me 55 Gold",
			"YOU_LOSE": "You lose 55 Gold",
			"TY": "Thank you for saving me !"
		}
};